@AIClientAPI_HostAddress = https://localhost:7076

POST {{AIClientAPI_HostAddress}}/AI
Content-Type: application/json
{
  "userMessage": "コミット履歴が恥ずかしい。でも GitHub で PR 出したい！ メモ。技術 Visual Studio。自分のコミット履歴が恥ずかしい、でも C# Tokyo のお題にチャレンジして PR したい！ そう考えていますね。大丈夫です、コミット履歴などきれいにする必要はありません。何なら既存を破壊するような PR を出しても大丈夫です！ 最後に整っていればそれでよいのですし、マージ後に最後に整えますので。それでもやっぱり恥ずかしい。わかります。私も恥ずかしいです。なので簡単にコミットをきれいにしつつ PR する手順で必要なコマンド等をメモしておきます。私自身が覚えられないので、スニペットとしておいておきたいので。"
}

###
